### ISSUE TITLE
运行 generate.py的时候报错，cudnn 已经安装了啊？

### ISSUE THREAD

**Issue by hopeforus** [Facico/Chinese-Vicuna#162]
(vicuna) hope@hope-08:~/work/Chinese-Vicuna$ python generate.py
Traceback (most recent call last):
  File "generate.py", line 2, in <module>
    import torch
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/torch/__init__.py", line 177, in _load_global_deps
    raise err
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudnn.so.8: cannot open shared object file: No such file or directory

**Comment by hopeforus** [comment]
谢谢，我重新安装了 cuda 12，cudnn 前面不报错了，新问题来了，在找原因，呵呵
(vicuna) hope@hope-08:~/work/Chinese-Vicuna/scripts$ bash generate.sh
Traceback (most recent call last):
  File "/home/hope/work/Chinese-Vicuna/generate.py", line 3, in <module>
    from peft import PeftModel, PeftModelForCausalLM, LoraConfig
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/peft/__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/peft/mapping.py", line 16, in <module>
    from .peft_model import (
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/peft/peft_model.py", line 22, in <module>
    from accelerate import dispatch_model, infer_auto_device_map
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/accelerate/accelerator.py", line 36, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/hope/miniconda3/envs/vicuna/lib/python3.8/site-packages/accelerate/tracking.py", line 49, in <module>
    import wandb
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/sdk/__init__.py", line 5, in <module>
    from .wandb_artifacts import Artifact  # noqa: F401
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 33, in <module>
    from wandb.apis import InternalApi, PublicApi
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/apis/__init__.py", line 42, in <module>
    from .internal import Api as InternalApi  # noqa
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/apis/internal.py", line 1, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 45, in <module>
    from ..lib import retry
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 10, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/hope/.local/lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 1, in <module>
    import google.protobuf
ModuleNotFoundError: No module named 'google.protobuf'

**Comment by Facico** [comment]
没有的库用pip或者conda装不就行了？
