### ISSUE TITLE
finetune_deepspeed使用load_in_8bit后，出现“RuntimeError: expected scalar type Float but found Half”

### ISSUE THREAD

**Issue by ryanzhangga1991** [Facico/Chinese-Vicuna#205]
您好，感谢提供了这么好项目。我学习到了很多Lora的技巧。
今天我在调试finetune_deepspeed时，因为我的显存有限（2x3090）加载 llama13B会OOM。
所以我修改了部分finetune_deepspeed.py的代码。
具体为：
```
if args.use8bit:
    model = LlamaForCausalLM.from_pretrained(
        args.model_path,
        load_in_8bit=True,
        device_map=device_map,
    )
    model = prepare_model_for_int8_training(model)
else:
    model = LlamaForCausalLM.from_pretrained(
        args.model_path,
        load_in_8bit=False,
        torch_dtype=torch.float16,
        device_map=device_map,
    ).half()
```
同时把zero_config.json中 "fp16"的 enabled改为auto。
量化后的确成功load，但是在train的时候发生了如下错误：
```
Traceback (most recent call last):
  File "/home/dlwork02/PycharmProjects/Chinese-Vicuna/finetune_deepspeed.py", line 313, in <module>
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
  File "/home/dlwork02/PycharmProjects/Chinese-Vicuna/finetune_deepspeed.py", line 313, in <module>
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 1636, in train
    return inner_training_loop(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 1903, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 1636, in train
    return inner_training_loop(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 2649, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 1903, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 2681, in compute_loss
    outputs = model(**inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 2649, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/trainer.py", line 2681, in compute_loss
    outputs = model(**inputs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1846, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/peft/peft_model.py", line 529, in forward
    return self.base_model(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/peft/peft_model.py", line 529, in forward
    return self.base_model(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 607, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 607, in forward
    layer_outputs = torch.utils.checkpoint.checkpoint(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 603, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 603, in custom_forward
    return module(*inputs, output_attentions, None)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 309, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/accelerate/hooks.py", line 156, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/transformers/models/llama/modeling_llama.py", line 209, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/peft/tuners/lora.py", line 532, in forward
    output = self.lora_B(self.lora_A(self.lora_dropout(x))).to(expected_dtype) * self.scaling
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/peft/tuners/lora.py", line 532, in forward
    output = self.lora_B(self.lora_A(self.lora_dropout(x))).to(expected_dtype) * self.scaling
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/dlwork02/.conda/envs/vicuna/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Float but found Half
```

**Comment by Facico** [comment]
这个脚本是专门给fp16用的，8bit的用finetune那个脚本。那个版本的deepspeed不支持8bit
